contact_links:
  - name: "💬 Discord"
    url: https://discord.gg/TBcnNX66PH
    about: Ask general questions here
  - name: "💬 Matrix"
    url: https://matrix.to/#/#navic:maize.moe
    about: Mirror of the Discord server, if you use Matrix
  - name: "⬇️ Downloads"
    url: https://github.com/paigely/Navic
    about: See the top of the README for downloads
