name: "💡 Feature Request"
description: Suggest a new feature/enhancement for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-explanation
    attributes:
      label: Feature explanation
      description: Brief explanation of what you want to be added
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Implementation guidance, screenshots/examples, etc
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: OS Version
      placeholder: Android 16, iOS 18...
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: App Version
      placeholder: eg. 1.0.0-alpha20
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Prerequisites
      options:
        - label: "I've checked existing issues to see if this already was requested"
          required: true
